"""add comments model

Revision ID: 000819bfd0bb
Revises: c0c75be6ef43
Create Date: 2022-05-08 21:13:30.099455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000819bfd0bb'
down_revision = 'c0c75be6ef43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('identity', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('pitch_title', sa.String(), nullable=True),
    sa.Column('pitch_comment', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.identity'], ),
    sa.PrimaryKeyConstraint('identity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
