"""change pitch id in children

Revision ID: d89a4813d6ee
Revises: 31497ddd1da2
Create Date: 2022-05-12 09:42:45.517412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89a4813d6ee'
down_revision = '31497ddd1da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id_comment', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id_comment'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'pitch_id')
    op.add_column('downvotes', sa.Column('pitch_id_downvote', sa.Integer(), nullable=True))
    op.drop_constraint('downvotes_pitch_id_fkey', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'pitches', ['pitch_id_downvote'], ['id'])
    op.drop_column('downvotes', 'pitch_id')
    op.add_column('upvotes', sa.Column('pitch_id_upvote', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_pitch_id_fkey', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id_upvote'], ['id'])
    op.drop_column('upvotes', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_pitch_id_fkey', 'upvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('upvotes', 'pitch_id_upvote')
    op.add_column('downvotes', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_pitch_id_fkey', 'downvotes', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('downvotes', 'pitch_id_downvote')
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitches', ['pitch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'pitch_id_comment')
    # ### end Alembic commands ###
