"""add user profile to user model

Revision ID: da43f494fa86
Revises: 000819bfd0bb
Create Date: 2022-05-08 23:09:38.636523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da43f494fa86'
down_revision = '000819bfd0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
